<?PHP

/**
 * @package config
 * @desc This is the default nomenclature for a project, you can make one by yourself
 * to fullfil your projects requirements
**/

$_SESSION['Nomenclature']=$Nomenclature=array(
'Proposal_Solicitude'=>'Solicitud de propuesta',
'Changes_Sheet'=>'Hoja de cambios',
'Changes_Sheet_Deleted'=>'Hoja de cambios eliminada',
'Gantt'=>'Diagrama de Gantt',
'Job_Entry'=>'Partidas de trabajo',
'Advance'=>'Avances',
'Show_Advances'=>'Mostrar avances',
'Gen_Advance'=>'Generar avance',
'Show_Secuence_Table'=>'Tabla de secuencia',
'Show_Asignation_Table'=>'Tabla de asignación',
'Job_Description'=>'Descripción del proyecto',
'ClientRequest'=>'Requerimientos del cliente',
'Supplies'=>'Insumos',
'AprovalsRequired'=>'Aprovaciones requeridas',
'ContractType'=>'Tipo de contrato',
'PayConditions'=>'Condiciones de pago',
'ProjectProgram'=>'Programa del proyecto',
'InstructionsContentFormat'=>'Formato y contenido',
'ExpiralDate'=>'Fecha de vencimiento',
'ThreadLine'=>'Linea de acción',
'Task'=>'Tarea',
'Proposal_Sheet_Deleted'=>'Hoja de propuesa eliminada',
//*************** Task administration
'Name'=>'Nombre',
'Description'=>'Descripción',
'Responsable'=>'Responsable',
'Cost'=>'Costo',
'Begin_Date'=>'Fecha de inicio',
'End_Date'=>'Fecha de termino',
'Programed_Begin'=>'Inicio programado',
'Programed_End'=>'Fin programado',
'Deliverable'=>'Producto',
'Deliverables'=>'Productos',
'Finished'=>'Terminado',
'Needs'=>'Requiere',
'Deleted_ActionThread'=>'Linea de acción eliminada',
'Deleted_Task'=>'Tarea eliminada',
'Deleted_Dependency'=>'Dependencia eliminada',
//PAGES TITLES .....................
'Project_Status_Title'=>'Estado del proyecto',
'Show_Advances_Title'=>'Mostrar avances',
'Generate_Advances_Title'=>'Reportar avances',
'Changes_Sheet_Title'=>'Hojas de cambios',
'Gantt_Diagram_Title'=>'Diagrama de Gantt',
'Job_Entry_Title'=>'Diagrama de partidas de trabajo',
'Proposal_Solicitude_Title'=>'Solicitud de propuesta',
'Secuence_Table_Title'=>'Tabla de secuencia',
'Asignation_Table_Title'=>'Tabla de asignación',
'Task_Admin_Title'=>'Administración de tareas',
'Reports_Title'=>'Reportes',
'Resource_Budget_Title'=>'Administración del presupuesto',
'Resource_Human_Title'=>'Recursos humanos',
'Resource_Material_Title'=>'Recursos materiales',
//MESSAGES FOR PAGES
'Add_Thread_Message'=>'Agregar linea de acción',
'Add_Task_Message'=>'Agregar tarea a linea de acción',
'Edit_Thread_Message'=>'Editar linea de acción',
'Delete_Thread_Message'=>'Eliminar linea de acción',
'Add_Dependency'=>'Agregar dependencia',
'Project_Selected'=>'Proyecto actual:',
//GANTT Diagram titles...
'No_Gantt'=>'Grafica de Gantt no disponible, verifica tu plan',
'Initial_Plan'=>'Plan inicial',
'Ajusted_Plan'=>'Plan ajustado',
'Real'=>'Real',
'Progress'=>'Progreso',
'Milestone'=>'Marca',
'Today'=>'Hoy',
'Last_Report'=>'Ultimo reporte',
'Begin_Task'=>'Iniciar tarea',
'End_Task'=>'Terminar tarea',
//Budget
'Budget'=>'Presupuesto',
'No_Budget'=>'No se encontraron presupuestos',
'Total_Cost'=>'Costo total',
'Total_Budget'=>'Presupuesto total',
'Amount'=>'Monto',
'Avaible'=>'Disponible',
'Expire_Date'=>'Fecha de expiración',
'New_Budget'=>'Nuevo presupuesto agregado',
'Delete_Budget'=>'Presupuesto eliminado',
'Use_Budget_Message'=>'Usar presupuesto',
'Use_Description'=>'Descripcion del uso',
'Budget_Used'=>'Se ha usado una parte del presupuesto y reportado en el log',
'Budget_Log'=>'Log del presupuesto',
//Material
'Material'=>'Material',
'New_Material'=>'Nuevo material agregado',
'Delete_Material'=>'Material eliminado',
'Material_Log'=>'Log del material',
'No_Material'=>'No se encontraron materiales',
'Serial'=>'Serial',
'No_Ended_Tasks'=>'No tienes tareas finalizadas',
'No_Asigned_Tasks'=>'No tienes tareas asignadas',
'Start_Task'=>'Declarar inicio de la tarea',
'End_Task'=>'Declarar fin de la tarea',
'Add_Advance'=>'Generar un avance',
'Task_Acepted_Status'=>'Estado de aceptacion de la tarea',
'Task_Begin_Reported'=>'Inicio real de la tarea reportado',
'Task_End_Reported'=>'Fin real de la tarea reportado',
'Task_Percent'=>'Porcentaje de la tarea',
'Advance_Reported'=>'Avance reportado',
'Total_Advance'=>'Avance total',
'Ended_Task'=>'Tareas finalizadas',
'Advance_Acepted'=>'Avance aceptado',
'Acept_Advance'=>'Aceptar avance',
//REPORTS----------------------------------------------------------
'Project_Report'=>'Datos del proyecto',
'Human_Resource_Report'=>'Recursos humanos',
'Proposal_Report'=>'Solicitud de propuesta',
''=>'',
//AUTOMATIC MESSAGES SENT WHEN TASKS ARE ADMINISTRATED
'New_Task_Message'=>'Se te ha asignado una nueva tarea, porfavor revisa los detalles de tu asignacion',
'New_Task_Assigned'=>'Nueva tarea asignada',
'Edited_Task_Message'=>'Se ha editado una tarea que tenias asignada, porfavor revisa los detalles',
'Edited_Task'=>'Tarea editada',
'New_Thread_Assigned'=>'Nueva linea de accion asignada',
'New_Thread_Message'=>'Se te ha asignado una linea de accion, porfavor revisa los detalles',
'Edited_Thread'=>'Linea de accion editada',
'Edited_Thread_Message'=>'Se edito una linea de accion que se te habia asignado, por favor revisa los detalles',
'New_ChangeSh_Title'=>'Nueva hoja de cambios',
'New_ChangeSh_Message'=>'Se ha generado una nueva hoja de cambios, pon atencion a los cambios en el proyecto',
'Edited_ChangeSh_Title'=>'Hoja de cambios editada',
'Edited_ChangeSh_Message'=>'Se ha editado una nueva hoja de cambios, revisa los cambios en el proyecto',
);
?>
